name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: Download
      run: |
        brew install cmake
        brew install python3
        brew install ninja
        git clone --depth=1 https://github.com/KhronosGroup/MoltenVK.git
        cd MoltenVK
        ./fetchDependencies --macos
        xcodebuild build -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)" -configuration "Release"
        find .
        zip -r Package.zip Package/
        
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: "macos-x64"
        path: "MoltenVK/Package.zip"
